version: "3"
services:
  webapp1:
    container_name: cont1
    image: meghashyam792/tryrepo:webapp3
    ports:
      - 1111:3000
    networks:
      - webapp1network

  webapp2:
    container_name: cont2
    image: meghashyam792/tryrepo:webapp2
    ports:
      - 2222:3000
    networks:
      - webapp2network

  webapp3:
    container_name: cont3
    image: meghashyam792/tryrepo:webapp3
    ports:
      - 3333:3000
    networks:
      - webapp3network

networks:
  webapp1network:
  webapp2network:
  webapp3network:

